### PR TITLE
Add multiple starting URLs

### PR DESCRIPTION
**Pull request by rafiramadhana**
Resolves https://github.com/philippta/flyscrape/issues/8

Add multiple starting URLs by adding `Module.URLs`.

### CODE REVIEW

**Comment by rafiramadhana** [comment]
@philippta  sry I haven't done any changes related to docs (e.g. config and example)

pls LMK which docs that should get updated

**Comment by philippta** [comment]
This is great, thanks!

**Examples**
If you like you can add an example under `examples/multiple_starting_urls.js`. 
For that, take the basic `hackernews.js` example, remove everthing from the config and add these two urls:
- https://news.ycombinator.com/show
- https://news.ycombinator.com/ask

**Documentation**
Don't mind the documentation for now. They currently still live in a private repo.

**Comment by rafiramadhana** [comment]
> If you like you can add an example under examples/multiple_starting_urls.js.

> Please document the urls option in between these two:

@philippta updated

**Comment by philippta** [comment]
Nice, thanks!

**Pull request merged**
